# Generated by Django 4.2.4 on 2023-09-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=400, verbose_name="Ijrochining to'liq ismi")),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Ijrochi ni rasmi')),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Ijrochi',
                'verbose_name_plural': 'Ijrochilar',
            },
        ),
    ]
