# Generated by Django 4.2.4 on 2023-09-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=500, verbose_name="Author to'liq ismi")),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Author ni rasmi')),
                ('book_number', models.CharField(max_length=20, verbose_name='Nechta kitob yozgani')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
    ]
