# Generated by Django 4.2.4 on 2023-09-05 04:42

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('author', '0001_initial'),
        ('performer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='Kitobni nomi')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='book/', verbose_name='Kitobni rasmi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='author.author', verbose_name='Kitobning Muallifi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='category.category', verbose_name="Janrlar bo'limi")),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per', to='performer.performer', verbose_name='Ijrochini Ism sharifi')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='FileBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio/', verbose_name='Faylni tanlang')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='book.book')),
            ],
            options={
                'verbose_name': 'Audio fayl',
                'verbose_name_plural': 'Audio fayllar',
            },
        ),
        migrations.CreateModel(
            name='BookRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(validators=[book.models.validate_number])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.book', verbose_name='Kitob nomi')),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
            },
        ),
    ]
