# Generated by Django 4.2.4 on 2023-09-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Kitob haqida '),
        ),
    ]
