# Generated by Django 4.2.4 on 2023-09-05 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_name', models.CharField(max_length=200, verbose_name='Kitob nomi')),
                ('author_name', models.CharField(max_length=400, verbose_name="Author to'liq ismi")),
                ('comment', models.TextField()),
                ('answers', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'new'), ('rejected', 'rejected'), ('completed', 'completed')], default='new', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zakas beruvchi',
                'verbose_name_plural': 'Zakas beruvchilar',
            },
        ),
    ]
